[tool.poetry]
name = "aml_subtype"
version = "0.1.0"
description = ""
authors = ["Rhea Chainani"]

[tool.poetry.dependencies]
python = "3.10.12"
tensorflow = "2.10.0"
numpy = "^1.23.5"
streamlit = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
